services:
    zicht_page.page_url_provider:
        class: Zicht\Bundle\PageBundle\Url\PageUrlProvider
        arguments:
            - @router
            - @zicht_page.page_manager
        tags:
            - { name: zicht_url.url_provider }

    zicht_page.page_aliaser:
        class: Zicht\Bundle\UrlBundle\Aliasing\Aliaser
        arguments:
            - @zicht_url.aliasing
            - @zicht_page.page_url_provider

    zicht_page.page_manager:
        class: Zicht\Bundle\PageBundle\Manager\PageManager
        arguments:
            - @doctrine
            - @event_dispatcher
            - ""
            - ""

    zicht_page.page_manager_subscriber:
        class: Zicht\Bundle\PageBundle\Manager\Doctrine\Subscriber
        arguments:
            - @service_container
        tags:
            - { name: doctrine.event_subscriber }

    zicht_page.form.type.zicht_content_item_type_type:
        class: Zicht\Bundle\PageBundle\Type\ContentItemTypeType
        arguments:
            - @sonata.admin.pool
            - ""
        tags:
            - { name: form.type, alias: zicht_content_item_type }

    zicht_page.form.type.zicht_content_item_region_type:
        class: Zicht\Bundle\PageBundle\Type\ContentItemRegionType
        arguments:
            - ""
            - ""
        tags:
            - { name: form.type, alias: zicht_content_item_region }

    # TODO move this type to ZichtFrameworkExtraBundle
    main.form.type.zicht_discriminator_map_type:
        class: Zicht\Bundle\PageBundle\Type\DiscriminatorMapType
        arguments:
            - @doctrine
        tags:
            - { name: form.type, alias: zicht_discriminator_map }

    zicht_page.admin.event_propagation_builder:
        class: Zicht\Bundle\PageBundle\AdminMenu\EventPropagationBuilder
        arguments:
            - @sonata.admin.pool
        tags:
            - { name: zicht_admin.event_propagation, event: 'zicht_page.view' }

