name: QA

on:
    pull_request:
        branches:
            - release/*

jobs:
    backend:
        runs-on: ubuntu-22.04
        strategy:
            matrix:
                php: [ '7.4', '8.1' ]
        name: PHP ${{ matrix.php }}
        steps:
            -   uses: actions/checkout@v3

            # https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    tools: cs2pr

            -   run: composer validate --strict
            -   run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
            -   run: composer install --prefer-dist --no-progress --no-scripts
            -   if: always()
                run: composer run-script lint -- --format=checkstyle | cs2pr
            -   if: always()
                run: composer run-script analysis -- --php-version=${{ matrix.php }} --no-suggestions --output-format=github
            -   if: always()
                run: composer run-script test

    translations:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-python@v3
                with:
                    python-version: '3.7'
            -   run: python -m pip install --upgrade pip
            -   run: pip install yaz_messaging_plugin
            -   run: yaz-messaging version
            -   run: yaz-messaging check
